### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by cheeta2018** [openstreetmap/Nominatim#1044]
Hello,I use the following command " ./utils/update.php --import-osmosis-all --no-npi" to update nominatim, it run normally last week, but it had a error on May 14, 2018 like this : 

/usr/bin/osmosis --read-replication-interval workingDirectory=/home/map/Downloads/Nominatim-2.5.1/settings --simplify-change --write-xml-change /home/map/Downloads/Nominatim-2.5.1/data/osmosischange.osc
May 14, 2018 10:49:43 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.44.1
May 14, 2018 10:49:43 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
May 14, 2018 10:49:43 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
May 14, 2018 10:49:43 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
May 14, 2018 10:49:44 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property.
	at org.openstreetmap.osmosis.replication.common.ReplicationState.loadProperty(ReplicationState.java:65)
	at org.openstreetmap.osmosis.replication.common.ReplicationState.load(ReplicationState.java:78)
	at org.openstreetmap.osmosis.replication.common.ReplicationState.<init>(ReplicationState.java:59)
	at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:108)
	at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:50)
	at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:290)
	at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:383)
	at java.lang.Thread.run(Thread.java:748)

May 14, 2018 10:49:44 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

Error: 1
Re-trying: /usr/bin/osmosis --read-replication-interval workingDirectory=/home/map/Downloads/Nominatim-2.5.1/settings --simplify-change --write-xml-change /home/map/Downloads/Nominatim-2.5.1/data/osmosischange.osc
May 14, 2018 10:50:44 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.44.1
May 14, 2018 10:50:44 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
May 14, 2018 10:50:44 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
May 14, 2018 10:50:44 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
May 14, 2018 10:50:45 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property.
	at org.openstreetmap.osmosis.replication.common.ReplicationState.loadProperty(ReplicationState.java:65)
	at org.openstreetmap.osmosis.replication.common.ReplicationState.load(ReplicationState.java:78)
	at org.openstreetmap.osmosis.replication.common.ReplicationState.<init>(ReplicationState.java:59)
	at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:108)
	at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:50)
	at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:290)
	at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:383)
	at java.lang.Thread.run(Thread.java:748)

May 14, 2018 10:50:45 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
	at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
	at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
	at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

Error: 1

So why this ? Is  there any way to resolve it?
Thank you very much!!!

**Comment by lonvia** [comment]
Please use the mailing list for questions.

**Comment by cheeta2018** [comment]
Sorry,I don't understand. Why can not answer here?

**Comment by cheeta2018** [comment]
@lonvia

**Comment by lonvia** [comment]
This is a bug tracker, not a Q&A site.

**Comment by cheeta2018** [comment]
So how to resolve it?
----- 原始邮件 -----
发件人：Sarah Hoffmann <notifications@github.com>
收件人：openstreetmap/Nominatim <Nominatim@noreply.github.com>
抄送人：cheeta2018 <yqvae@sina.com>,  Author <author@noreply.github.com>
主题：Re: [openstreetmap/Nominatim] Failed to update (#1044)
日期：2018年05月15日 17点39分

This is a bug tracker, not a Q&A site.

&mdash;

**Comment by cheeta2018** [comment]
Thank you very much!!!
