### ISSUE TITLE
Database query failed: relation "import_status" does not exist

### ISSUE THREAD

**Issue by jah-** [openstreetmap/Nominatim#1568]
Hi! I finnally import the world into my instance whit some tunnig in postregsl.conf and more RAM than the minimal resources checklist provided in the documentation.

The command line what I used for the import was:

`osm2pgsql   --verbose --flat-nodes planet.bin --cache 128000 --number-processes 16 --unlogged --cache-strategy dense --extra-attributes --slim  -d nominatim --style /usr/share/osm2pgsql/default.style planet-latest.osm.pbf 2>&1 | tee setup.log `

But now I have an issue to access to frontend (apache) the error is:

<pre> 

Internal Server Error

Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software.
Details
Database query failed

Exception Nominatim\DatabaseError thrown in /srv/nominatim/Nominatim-3.4.0/lib/DB.php(187).
SQL Error
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "import_status" does not exist LINE 1: ...lastimportdate,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta... ^

PDOException::__set_state(array(
   'message' => 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "import_status" does not exist
LINE 1: ...lastimportdate,\'YYYY/MM/DD HH24:MI\')||\' GMT\' from import_sta...
                                                             ^',
   'string' => '',
   'code' => '42P01',
   'file' => '/srv/nominatim/Nominatim-3.4.0/lib/DB.php',
   'line' => 184,
   'trace' => 
  array (
    0 => 
    array (
      'file' => '/srv/nominatim/Nominatim-3.4.0/lib/DB.php',
      'line' => 184,
      'function' => 'query',
      'class' => 'PDO',
      'type' => '->',
      'args' => 
      array (
        0 => 'select TO_CHAR(lastimportdate,\'YYYY/MM/DD HH24:MI\')||\' GMT\' from import_status limit 1',
      ),
    ),
    1 => 
    array (
      'file' => '/srv/nominatim/Nominatim-3.4.0/lib/DB.php',
      'line' => 96,
      'function' => 'getQueryStatement',
      'class' => 'Nominatim\\DB',
      'type' => '->',
      'args' => 
      array (
        0 => 'select TO_CHAR(lastimportdate,\'YYYY/MM/DD HH24:MI\')||\' GMT\' from import_status limit 1',
        1 => NULL,
        2 => 'Database query failed',
      ),
    ),
    2 => 
    array (
      'file' => '/srv/nominatim/Nominatim-3.4.0/website/search.php',
      'line' => 70,
      'function' => 'getOne',
      'class' => 'Nominatim\\DB',
      'type' => '->',
      'args' => 
      array (
        0 => 'select TO_CHAR(lastimportdate,\'YYYY/MM/DD HH24:MI\')||\' GMT\' from import_status limit 1',
      ),
    ),
    3 => 
    array (
      'file' => '/srv/nominatim/Nominatim-3.4.0/build/website/search.php',
      'line' => 3,
      'args' => 
      array (
        0 => '/srv/nominatim/Nominatim-3.4.0/website/search.php',
      ),
      'function' => 'require_once',
    ),
  ),
   'previous' => NULL,
   'errorInfo' => 
  array (
    0 => '42P01',
    1 => 7,
    2 => 'ERROR:  relation "import_status" does not exist
LINE 1: ...lastimportdate,\'YYYY/MM/DD HH24:MI\')||\' GMT\' from import_sta...
                                                             ^',
  ),
))

Stack trace

#0 /srv/nominatim/Nominatim-3.4.0/lib/DB.php(96): Nominatim\DB->getQueryStatement('select TO_CHAR(...', NULL, 'Database query ...')
#1 /srv/nominatim/Nominatim-3.4.0/website/search.php(70): Nominatim\DB->getOne('select TO_CHAR(...')
#2 /srv/nominatim/Nominatim-3.4.0/build/website/search.php(3): require_once('/srv/nominatim/...')
#3 {main}

If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used. </pre>

The relations in the database do not include the "import_status" relation.

<pre>
nominatim=# \dt
                List of relations
 Schema |        Name        | Type  |   Owner
--------+--------------------+-------+-----------
 public | planet_osm_line    | table | nominatim
 public | planet_osm_nodes   | table | nominatim
 public | planet_osm_point   | table | nominatim
 public | planet_osm_polygon | table | nominatim
 public | planet_osm_rels    | table | nominatim
 public | planet_osm_roads   | table | nominatim
 public | planet_osm_ways    | table | nominatim
 public | spatial_ref_sys    | table | postgres
(8 rows)
</pre>

Thanks in advance!

**Comment by mtmail** [comment]
The setup hasn't finished yet. Nominatim will create hundreds of tables. What are the last lines in the `setup.log` ? Does the postgresql server log file indicate any crashes?

http://nominatim.org/release-docs/3.4.0/admin/Import-and-Update/

**Comment by jah-** [comment]
Hi mtmail, thanks for your comments.

Last lines of setup.log:

<pre>
Copying planet_osm_polygon to cluster by geometry finished
Creating geometry index on planet_osm_polygon
Creating osm_id index on planet_osm_polygon
Creating indexes on planet_osm_polygon finished
All indexes on planet_osm_polygon created in 24501s
Completed planet_osm_polygon
Stopped table: planet_osm_ways in 27071s
node cache: stored: 5554773687(100.00%), storage efficiency: 80.27% (dense blocks: 844770, sparse nodes: 0), hit rate: 100.00%

Osm2pgsql took 59202s overall
</pre>

postgres errors extract:

<pre>
/var/log/postgresql$ grep -i error postgresql-10-main.log|sort -u
2019-11-11 09:45:19.752 UTC [8037] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 09:45:19.752 UTC [8038] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 09:45:19.752 UTC [8039] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 09:45:19.752 UTC [8040] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 09:45:19.752 UTC [8041] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 09:46:31.566 UTC [8165] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-11 09:50:38.020 UTC [8202] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-11 15:11:21.053 UTC [10998] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11019] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11021] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11025] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11026] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11027] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11028] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11032] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11034] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11039] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11040] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11041] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11042] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11046] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11047] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11048] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11049] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11053] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11055] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11056] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11060] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11061] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11062] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11063] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11067] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11068] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11069] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11070] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11074] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11075] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11076] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11077] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11081] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11082] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11083] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.053 UTC [11084] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11000] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11004] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11005] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11006] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11007] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11011] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11014] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.054 UTC [11018] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.056 UTC [10999] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.056 UTC [11054] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.057 UTC [11012] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.057 UTC [11013] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.057 UTC [11020] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.058 UTC [11033] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.058 UTC [11035] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-11 15:11:21.060 UTC [10997] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 05:36:54.923 UTC [11725] nominatim@nominatim ERROR:  could not write block 12317267 of temporary file: No space left on device
2019-11-12 05:36:54.923 UTC [11728] nominatim@nominatim ERROR:  could not extend file "base/2396232/9186540.155": No space left on device
2019-11-12 11:48:00.899 UTC [19627] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-12 13:48:14.479 UTC [2191] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2203] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2204] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2205] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2206] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2207] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2208] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-12 13:50:23.714 UTC [2209] nominatim@nominatim ERROR:  unexpected EOF on client connection with an open transaction
2019-11-13 10:48:16.076 UTC [27757] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 10:50:15.595 UTC [27812] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 10:50:19.955 UTC [27813] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 10:51:07.379 UTC [27813] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 10:53:11.095 UTC [27812] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 10:54:00.528 UTC [27826] www-data@nominatim ERROR:  relation "placex" does not exist at character 149
2019-11-13 10:54:13.937 UTC [27757] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:13:29.583 UTC [27812] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:25:55.993 UTC [29656] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:33:39.968 UTC [29811] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:34:04.726 UTC [29815] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:34:51.789 UTC [29811] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:45:07.769 UTC [30002] www-data@nominatim ERROR:  function make_standard_name(unknown) does not exist at character 8
2019-11-13 14:45:26.025 UTC [29811] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:45:31.352 UTC [29815] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:45:34.808 UTC [30005] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:48:59.006 UTC [30119] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:49:04.464 UTC [30120] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:49:39.846 UTC [30129] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:50:38.131 UTC [30168] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:50:46.628 UTC [30169] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:50:55.912 UTC [30168] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 14:52:04.965 UTC [30169] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 17:33:31.003 UTC [31088] www-data@nominatim ERROR:  function make_standard_name(unknown) does not exist at character 8
2019-11-13 17:33:36.444 UTC [30168] www-data@nominatim ERROR:  function make_standard_name(unknown) does not exist at character 8
2019-11-13 17:34:00.182 UTC [31090] www-data@nominatim ERROR:  function make_standard_name(unknown) does not exist at character 8
2019-11-13 17:34:26.925 UTC [31004] postgres@nominatim ERROR:  relation "places" does not exist at character 22
2019-11-13 17:34:37.430 UTC [31004] postgres@nominatim ERROR:  relation "placex" does not exist at character 38
2019-11-13 17:34:43.627 UTC [31004] postgres@nominatim ERROR:  relation "import_status" does not exist at character 15
2019-11-13 17:35:57.857 UTC [31098] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 17:36:08.076 UTC [30168] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 17:36:23.251 UTC [31090] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
2019-11-13 17:39:46.533 UTC [31098] www-data@nominatim ERROR:  relation "import_status" does not exist at character 66
</pre>

**Comment by mmd-osm** [comment]
Looks like your disk is full:

2019-11-12 05:36:54.923 UTC [11725] nominatim@nominatim ERROR:  could not write block 12317267 of temporary file: **No space left on device**
2019-11-12 05:36:54.923 UTC [11728] nominatim@nominatim ERROR:  could not extend file "base/2396232/9186540.155": **No space left on device**

**Comment by mtmail** [comment]
Thanks @mmd-osm , I missed that.

**Comment by jah-** [comment]
The disk is fine I watch the disk usage whit an shell script, I have  a 2TB ssd, the disk usage is around 800GB, only used by nominatim stack.

I compare the reations in other setup (docker based) and I saw a lots of tables, that's not in this case:

<pre>
nominatim=# \dt
                List of relations
 Schema |        Name        | Type  |   Owner
--------+--------------------+-------+-----------
 public | planet_osm_line    | table | nominatim
 public | planet_osm_nodes   | table | nominatim
 public | planet_osm_point   | table | nominatim
 public | planet_osm_polygon | table | nominatim
 public | planet_osm_rels    | table | nominatim
 public | planet_osm_roads   | table | nominatim
 public | planet_osm_ways    | table | nominatim
 public | spatial_ref_sys    | table | postgres
(8 rows)
</pre>

I run again de process whit this parameters, after drop the db:

`~/Nominatim-3.4.0/build$ ./utils/setup.php --osm-file ../data/planet-latest.osm.pbf --all --osm2pgsql-cache 128000 2>&1 | tee setup1.log`

Thanks for your reply.

**Comment by mmd-osm** [comment]
There must be some reason for those messages. Are you sure you have enough space on all relevant partitions, including /tmp?

**Comment by jah-** [comment]
Hi, in my opinion there's enogh space in the disks:
<pre>
Filesystem      Size  Used Avail Use% Mounted on
udev            125G     0  125G   0% /dev
tmpfs            25G  940K   25G   1% /run
/dev/nvme0n1p1  1.9T  350G  1.6T  19% /
tmpfs           125G   32K  125G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           125G     0  125G   0% /sys/fs/cgroup
/dev/loop0       18M   18M     0 100% /snap/amazon-ssm-agent/1480
/dev/loop1       90M   90M     0 100% /snap/core/7917
/dev/loop2       90M   90M     0 100% /snap/core/8039
tmpfs            25G     0   25G   0% /run/user/1000
</pre>

I think about kernel limits or something similar stuff, before the last exec of the import, I.e: I modify "vm.overcommit_memory=1" 

I saw the message in the setup.log

<pre>
Osm2pgsql failed due to ERROR: CREATE TABLE planet_osm_polygon_tmp  AS
  SELECT * FROM planet_osm_polygon
    WHERE ST_IsValid(way)
    ORDER BY ST_GeoHash(ST_Transform(ST_Envelope(way),4326),10)
    COLLATE "C" failed: ERROR:  could not write block 12317267 of temporary file: No space left on device
</pre>

<pre>
Wed-14:05:29
 /dev/nvme0n1p1 1.9T 965G 975G 50% /
</pre>

the disk usage pasted above is the status when the import ends.

Thanks again!

**Comment by jah-** [comment]
Hi, in my opinion there's enogh space in the disks:
<pre>
Filesystem      Size  Used Avail Use% Mounted on
udev            125G     0  125G   0% /dev
tmpfs            25G  940K   25G   1% /run
/dev/nvme0n1p1  1.9T  350G  1.6T  19% /
tmpfs           125G   32K  125G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           125G     0  125G   0% /sys/fs/cgroup
/dev/loop0       18M   18M     0 100% /snap/amazon-ssm-agent/1480
/dev/loop1       90M   90M     0 100% /snap/core/7917
/dev/loop2       90M   90M     0 100% /snap/core/8039
tmpfs            25G     0   25G   0% /run/user/1000
</pre>

I think about kernel limits or something similar stuff, before the last exec of the import, I.e: I modify "vm.overcommit_memory=1" 

I saw the message in the setup.log

<pre>
Osm2pgsql failed due to ERROR: CREATE TABLE planet_osm_polygon_tmp  AS
  SELECT * FROM planet_osm_polygon
    WHERE ST_IsValid(way)
    ORDER BY ST_GeoHash(ST_Transform(ST_Envelope(way),4326),10)
    COLLATE "C" failed: ERROR:  could not write block 12317267 of temporary file: No space left on device
</pre>

<pre>
Wed-14:05:29
 /dev/nvme0n1p1 1.9T 965G 975G 50% /
</pre>

the disk usage pasted above is the status when the import ends.

Thanks again!

**Comment by jah-** [comment]
The disk is fine I watch the disk usage whit an shell script, I have  a 2TB ssd, the disk usage is around 800GB, only used by nominatim stack.

I compare the relations in another setup (docker based) and I saw a lots of tables, that's not in this case:

<pre>
nominatim=# \dt
                List of relations
 Schema |        Name        | Type  |   Owner
--------+--------------------+-------+-----------
 public | planet_osm_line    | table | nominatim
 public | planet_osm_nodes   | table | nominatim
 public | planet_osm_point   | table | nominatim
 public | planet_osm_polygon | table | nominatim
 public | planet_osm_rels    | table | nominatim
 public | planet_osm_roads   | table | nominatim
 public | planet_osm_ways    | table | nominatim
 public | spatial_ref_sys    | table | postgres
(8 rows)
</pre>

I run again de process whit this parameters, after drop the db:

`~/Nominatim-3.4.0/build$ ./utils/setup.php --osm-file ../data/planet-latest.osm.pbf --all --osm2pgsql-cache 128000 2>&1 | tee setup1.log`

Thanks for your reply.

**Comment by lonvia** [comment]
We really can't help you with your generic setup. You'll have to debug yourself what's wrong with your discs and why you run out of space. It doesn't look like Nominatim is at fault and therefore off-topic for this issue tracker. Closing.

**Comment by jah-** [comment]
thanks for yor time @lonvia!
