### ISSUE TITLE
IOError from tigerAddressImport.py

### ISSUE THREAD

**Issue by ARSimmons** [openstreetmap/Nominatim#664]
Unpacking Tiger on a 2TB drive (home of both the postgresql data folder and the Tiger data) ... the drive was hovering around 40% before the Tiger unpack. Now it is claiming it is full(?)

```
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim/utils/tigerAddressImport.py", line 4162, in <module>
    shape_to_osm( shape, osm, id )
  File "/srv/nominatim/Nominatim/utils/tigerAddressImport.py", line 4070, in shape_to_osm
    fp.write( "\n".join( ret ) )
IOError: [Errno 28] No space left on device
Processing 24019...
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim/utils/tigerAddressImport.py", line 4162, in <module>
    shape_to_osm( shape, osm, id )
  File "/srv/nominatim/Nominatim/utils/tigerAddressImport.py", line 4146, in shape_to_osm
    fp.write( "\n".join( ret ) )
IOError: [Errno 28] No space left on device
Processing 24021...

/tmp/tigerbUzb80/tl_2015_24021_edges.shp:  write error (disk full?).  Continue? (y/n/^C)
```
...how can I better set up this process (and back out what I have currently imported?)...

**Comment by lonvia** [comment]
The complete Tiger data needs around 9GB disk space after preprocessing. That's not your problem, your problem is obviously that /tmp is too small.

**Comment by ARSimmons** [comment]
Ah! gotcha.

**Comment by ARSimmons** [comment]
thanks!
